Repository chainwayxyz/clementine, pull requests merged in 2025-06, with the labels that each got.

#779 Update crate documentation
  README.md
  core/src/lib.rs
Labels: P-Medium

#776 Extended RPC unit tests and documentation
  .github/workflows/build_and_test.yml
  core/src/database/header_chain_prover.rs
  core/src/extended_rpc.rs
  core/src/test/additional_disprove_scripts.rs
  core/src/test/deposit_and_withdraw_e2e.rs
  core/src/test/full_flow.rs
Labels: P-Medium

#772 Add feature flag for automations (State Machine, TxSender)
  .github/workflows/build_and_test.yml
  .github/workflows/code_checks.yml
  README.md
  core/Cargo.toml
  core/src/aggregator.rs
  core/src/bin/cli.rs
  core/src/bitcoin_syncer.rs
  core/src/builder/block_cache.rs
  core/src/builder/mod.rs
  core/src/builder/transaction/creator.rs
  core/src/builder/transaction/sign.rs
  core/src/database/mod.rs
  core/src/database/tx_sender.rs
  core/src/errors.rs
  core/src/header_chain_prover.rs
  core/src/lib.rs
  core/src/operator.rs
  core/src/rpc/aggregator.rs
  core/src/rpc/clementine.proto
  core/src/rpc/clementine.rs
  core/src/rpc/operator.rs
  core/src/rpc/parser/mod.rs
  core/src/rpc/verifier.rs
  core/src/states/block_cache.rs
  core/src/states/context.rs
  core/src/states/mod.rs
  core/src/states/task.rs
  core/src/task/manager.rs
  core/src/task/payout_checker.rs
  core/src/task/tests.rs
  core/src/test/additional_disprove_scripts.rs
  core/src/test/common/mod.rs
  core/src/test/common/setup_utils.rs
  core/src/test/common/tx_utils.rs
  core/src/test/deposit_and_withdraw_e2e.rs
  core/src/test/full_flow.rs
  core/src/test/mod.rs
  core/src/tx_sender/client.rs
  core/src/tx_sender/cpfp.rs
  core/src/tx_sender/mod.rs
  core/src/tx_sender/rbf.rs
  core/src/utils.rs
  core/src/verifier.rs
  scripts/run-deposit.sh
  scripts/run-test.sh
  scripts/run.sh
Labels: P-High

#807 Deposit data check
  core/src/database/operator.rs
  core/src/deposit.rs
  core/src/errors.rs
  core/src/verifier.rs
Labels: P-High

#806 Remove some of the TODOs
  .github/workflows/code_checks.yml
  Cargo.lock
  Cargo.toml
  bridge-circuit-host/src/docker.rs
  bridge-circuit-host/src/utils.rs
  circuits-lib/src/bridge_circuit/mod.rs
  core/src/actor.rs
  core/src/bin/cli.rs
  core/src/bitcoin_syncer.rs
  core/src/builder/sighash.rs
  core/src/builder/transaction/challenge.rs
  core/src/builder/transaction/creator.rs
  core/src/builder/transaction/sign.rs
  core/src/builder/transaction/txhandler.rs
  core/src/config/protocol.rs
  core/src/constants.rs
  core/src/database/bitcoin_syncer.rs
  core/src/database/header_chain_prover.rs
  core/src/database/operator.rs
  core/src/database/verifier.rs
  core/src/errors.rs
  core/src/extended_rpc.rs
  core/src/header_chain_prover.rs
  core/src/lib.rs
  core/src/operator.rs
  core/src/rpc/aggregator.rs
  core/src/rpc/clementine.proto
  core/src/rpc/clementine.rs
  core/src/rpc/mod.rs
  core/src/rpc/operator.rs
  core/src/rpc/parser/mod.rs
  core/src/rpc/parser/operator.rs
  core/src/servers.rs
  core/src/states/event.rs
  core/src/states/kickoff.rs
  core/src/states/mod.rs
  core/src/states/task.rs
  core/src/task/payout_checker.rs
  core/src/task/tests.rs
  core/src/test/additional_disprove_scripts.rs
  core/src/test/common/citrea/parameters.rs
  core/src/test/common/citrea/requests.rs
  core/src/test/common/mod.rs
  core/src/test/common/setup_utils.rs
  core/src/test/deposit_and_withdraw_e2e.rs
  core/src/tx_sender/client.rs
  core/src/tx_sender/mod.rs
  core/src/tx_sender/rbf.rs
  core/src/tx_sender/task.rs
  core/src/verifier.rs
Labels: P-High

#811 First round
  core/src/actor.rs
  core/src/builder/script.rs
  core/src/builder/sighash.rs
  core/src/builder/transaction/creator.rs
  core/src/builder/transaction/input.rs
  core/src/builder/transaction/mod.rs
  core/src/builder/transaction/operator_collateral.rs
  core/src/builder/transaction/sign.rs
  core/src/database/operator.rs
  core/src/deposit.rs
  core/src/extended_rpc.rs
  core/src/operator.rs
  core/src/rpc/parser/mod.rs
  core/src/states/context.rs
  core/src/states/round.rs
  core/src/test/additional_disprove_scripts.rs
  core/src/test/common/mod.rs
  core/src/test/deposit_and_withdraw_e2e.rs
  core/src/test/full_flow.rs
  core/src/tx_sender/client.rs
  core/src/utils.rs
  core/src/verifier.rs
Labels: P-High

#818 Update secp version and patch
  Cargo.lock
  Cargo.toml
  core/src/actor.rs
  core/src/aggregator.rs
  core/src/bitvm_client.rs
  core/src/builder/address.rs
  core/src/builder/script.rs
  core/src/database/wrapper.rs
  core/src/deposit.rs
  core/src/musig2.rs
  core/src/rpc/aggregator.rs
  core/src/rpc/parser/verifier.rs
  core/src/rpc/verifier.rs
  core/src/test/common/mod.rs
  core/src/test/musig2.rs
  core/src/tx_sender/mod.rs
  core/src/verifier.rs
Labels: code quality, P-Low, Deposit Replace Needed

#828 Annex support
  bridge-circuit-host/src/utils.rs
  circuits-lib/src/bridge_circuit/groth16_verifier.rs
  circuits-lib/src/bridge_circuit/mod.rs
  circuits-lib/src/bridge_circuit/structs.rs
  circuits-lib/src/common/mod.rs
  circuits-lib/src/common/utils.rs
  core/src/cli.rs
  core/src/config/protocol.rs
  core/src/test/data/protocol_paramset.toml
  risc0-circuits/elfs/mainnet-bridge-circuit-guest.bin
  risc0-circuits/elfs/mainnet-header-chain-guest.bin
  risc0-circuits/elfs/regtest-bridge-circuit-guest.bin
  risc0-circuits/elfs/regtest-header-chain-guest.bin
  risc0-circuits/elfs/signet-bridge-circuit-guest.bin
  risc0-circuits/elfs/signet-header-chain-guest.bin
  risc0-circuits/elfs/testnet4-bridge-circuit-guest.bin
  risc0-circuits/elfs/testnet4-header-chain-guest.bin
Labels: F-deposit-replace-needed

#827 Add timeouts to Aggregator::new_deposit
  core/Cargo.toml
  core/src/aggregator.rs
  core/src/config/mod.rs
  core/src/config/test.rs
  core/src/constants.rs
  core/src/database/mod.rs
  core/src/errors.rs
  core/src/operator.rs
  core/src/rpc/aggregator.rs
  core/src/rpc/operator.rs
  core/src/rpc/parser/verifier.rs
  core/src/rpc/verifier.rs
  core/src/test/common/mod.rs
  core/src/test/common/tx_utils.rs
  core/src/test/deposit_and_withdraw_e2e.rs
  core/src/utils.rs
  core/src/verifier.rs
Labels: S-HOLD-MERGE

#883 Separate unit and integration tests
  .cargo/config.toml
  .github/workflows/build_and_test.yml
  README.md
  core/Cargo.toml
  core/src/lib.rs
  core/src/test/common/citrea/client_mock.rs
  core/src/test/common/mod.rs
  core/src/test/mod.rs
Labels: T-enhancement, P-medium, S-review

#850 Sighash breaking change test
  .github/workflows/auto_tag.yml
  README.md
  core/src/builder/sighash.rs
  core/src/builder/transaction/creator.rs
  core/src/builder/transaction/deposit_signature_owner.rs
  core/src/builder/transaction/operator_collateral.rs
  core/src/builder/transaction/sign.rs
  core/src/config/test.rs
  core/src/database/mod.rs
  core/src/extended_rpc.rs
  core/src/operator.rs
  core/src/rpc/aggregator.rs
  core/src/test/additional_disprove_scripts.rs
  core/src/test/bitvm_disprove_scripts.rs
  core/src/test/common/mod.rs
  core/src/test/common/setup_utils.rs
  core/src/test/data/deposit_state_debug.bincode
  core/src/test/data/deposit_state_release.bincode
  core/src/test/deposit_and_withdraw_e2e.rs
  core/src/test/watchtower_challenge.rs
Labels: P-high, F-deposit-replace-needed
